;;;; Copyright (c) 2024-2026 Parkian Company LLC. All rights reserved.
;;;; SPDX-License-Identifier: Apache-2.0
;;;; This file is part of cl-secp256k1.

;;;; ECDSA (Elliptic Curve Digital Signature Algorithm) for secp256k1
;;;;
;;;; Standards:
;;;; - FIPS 186-5: Digital Signature Standard (DSS)
;;;; - SEC 1: Elliptic Curve Cryptography (point encoding)
;;;; - RFC 6979: Deterministic nonce generation
;;;; - BIP-62: Low-S signature normalization

(in-package #:cl-secp256k1)

;;; ============================================================================
;;; Key Generation and Validation
;;; ============================================================================

(defun generate-private-key ()
  "Generate a random 256-bit private key.

   RETURNS:
   A random integer in range [1, n-1] suitable as a private key.

   SECURITY:
   Uses cryptographically secure random bytes from /dev/urandom."
  (let ((bytes (random-bytes 32)))
    (loop for result = (bytes-to-integer bytes)
          while (or (zerop result) (>= result +secp256k1-n+))
          do (setf bytes (random-bytes 32))
             (setf result (bytes-to-integer bytes))
          finally (return result))))

(defun private-key-to-public (private-key)
  "Derive public key point from private key scalar.

   PARAMETERS:
   - PRIVATE-KEY: Integer in range [1, n-1]

   RETURNS:
   Public key point (x . y) = private_key * G"
  (point-multiply private-key (generator-point)))

(defun valid-private-key-p (key)
  "Check if KEY is a valid secp256k1 private key.

   A valid private key is an integer in range [1, n-1]."
  (and (integerp key)
       (plusp key)
       (< key +secp256k1-n+)))

(defun valid-public-key-p (point)
  "Check if POINT is a valid secp256k1 public key.

   A valid public key is a point on the curve (not infinity)
   in the group generated by G."
  (and (not (point-at-infinity-p point))
       (valid-point-p point)))

;;; ============================================================================
;;; Public Key Serialization (SEC1 Format)
;;; ============================================================================

(defun serialize-public-key (point &key (compressed t))
  "Serialize public key to bytes in SEC1 format.

   PARAMETERS:
   - POINT: Public key point (x . y)
   - COMPRESSED: If T (default), output 33-byte compressed format.
                 If NIL, output 65-byte uncompressed format.

   FORMATS:
   - Compressed (33 bytes): 0x02/0x03 || x
     (prefix indicates y parity)
   - Uncompressed (65 bytes): 0x04 || x || y

   RETURNS:
   Byte vector of serialized public key"
  (if (point-at-infinity-p point)
      (make-array 1 :element-type '(unsigned-byte 8) :initial-element 0)
      (let ((x-bytes (integer-to-bytes (car point) 32))
            (y-bytes (integer-to-bytes (cdr point) 32)))
        (if compressed
            (let ((result (make-array 33 :element-type '(unsigned-byte 8))))
              ;; 0x02 if y is even, 0x03 if y is odd
              (setf (aref result 0) (if (evenp (cdr point)) #x02 #x03))
              (replace result x-bytes :start1 1)
              result)
            (let ((result (make-array 65 :element-type '(unsigned-byte 8))))
              (setf (aref result 0) #x04)
              (replace result x-bytes :start1 1)
              (replace result y-bytes :start1 33)
              result)))))

(defun parse-public-key (bytes)
  "Parse SEC1 encoded public key bytes to point.

   PARAMETERS:
   - BYTES: Byte vector (33 bytes compressed, 65 bytes uncompressed)

   RETURNS:
   Point (x . y)

   SIGNALS ERROR:
   If format is invalid"
  (let ((prefix (aref bytes 0)))
    (cond
      ((= prefix #x04)
       ;; Uncompressed: 0x04 || x || y
       (unless (= (length bytes) 65)
         (error "Invalid uncompressed public key length"))
       (cons (bytes-to-integer (subseq bytes 1 33))
             (bytes-to-integer (subseq bytes 33 65))))
      ((or (= prefix #x02) (= prefix #x03))
       ;; Compressed: 0x02/0x03 || x
       (unless (= (length bytes) 33)
         (error "Invalid compressed public key length"))
       (let* ((x (bytes-to-integer (subseq bytes 1 33)))
              (y (decompress-y x (= prefix #x03))))
         (unless y
           (error "Invalid compressed public key: x not on curve"))
         (cons x y)))
      (t
       (error "Invalid public key format: unknown prefix ~2,'0X" prefix)))))

(defun decompress-y (x is-odd)
  "Compute y coordinate from x and parity bit.

   For secp256k1: y^2 = x^3 + 7 (mod p)

   Since p = 3 (mod 4), we can compute sqrt as:
   y = (x^3 + 7)^((p+1)/4) mod p

   PARAMETERS:
   - X: x coordinate
   - IS-ODD: T if y should be odd, NIL if even

   RETURNS:
   y coordinate, or NIL if x is not on curve"
  (let* ((p +secp256k1-p+)
         (y-squared (mod (+ (* x x x) 7) p))
         ;; y = y_squared^((p+1)/4) mod p
         (y (mod-expt y-squared (ash (1+ p) -2) p)))
    ;; Verify this is actually a square root
    (unless (= (mod (* y y) p) y-squared)
      (return-from decompress-y nil))
    ;; Adjust parity
    (if (eq (oddp y) is-odd)
        y
        (- p y))))

;;; ============================================================================
;;; ECDSA Signing
;;; ============================================================================

(defun ecdsa-sign (message-hash private-key)
  "Sign MESSAGE-HASH with PRIVATE-KEY using ECDSA.

   Uses RFC 6979 deterministic nonce generation to prevent nonce reuse
   attacks. Applies BIP-62 low-S normalization for malleability fix.

   PARAMETERS:
   - MESSAGE-HASH: 32-byte hash of message (e.g., SHA-256 output)
   - PRIVATE-KEY: Integer or 32-byte vector

   RETURNS:
   Signature (r . s) pair

   ALGORITHM:
   1. k = RFC6979(private_key, message_hash)
   2. (x, y) = k * G
   3. r = x mod n
   4. s = k^(-1) * (z + r*d) mod n
   5. If s > n/2, set s = n - s (low-S normalization)

   SECURITY:
   - Deterministic: Same inputs always produce same signature
   - No RNG dependency for nonce
   - Low-S prevents signature malleability"
  (let* ((n +secp256k1-n+)
         ;; Convert inputs to appropriate formats
         (private-key-bytes (if (vectorp private-key)
                                private-key
                                (integer-to-bytes private-key 32)))
         (private-key-int (if (integerp private-key)
                              private-key
                              (bytes-to-integer private-key)))
         (message-hash-bytes (if (vectorp message-hash)
                                 message-hash
                                 (integer-to-bytes message-hash 32)))
         (z (if (vectorp message-hash)
                (bytes-to-integer message-hash)
                message-hash))
         ;; Generate deterministic k using RFC 6979
         (k (rfc6979-generate-k private-key-bytes message-hash-bytes))
         ;; Compute r = (k*G).x mod n
         (point (point-multiply k (generator-point)))
         (r (mod (car point) n)))
    ;; r should not be zero (extremely unlikely with RFC 6979)
    (when (zerop r)
      (error "RFC 6979 produced r=0; this should never happen"))
    ;; Compute s = k^(-1) * (z + r*d) mod n
    (let* ((k-inv (mod-inverse k n))
           (s (mod (* k-inv (+ z (* r private-key-int))) n)))
      ;; s should not be zero
      (when (zerop s)
        (error "RFC 6979 produced s=0; this should never happen"))
      ;; Use low-s value (BIP-62 malleability fix)
      (when (> s (ash n -1))
        (setf s (- n s)))
      (cons r s))))

(defun ecdsa-sign-hash (hash private-key)
  "Sign a pre-computed hash. Alias for ECDSA-SIGN."
  (ecdsa-sign hash private-key))

;;; ============================================================================
;;; ECDSA Verification
;;; ============================================================================

(defun ecdsa-verify (message-hash signature public-key)
  "Verify ECDSA SIGNATURE on MESSAGE-HASH with PUBLIC-KEY.

   PARAMETERS:
   - MESSAGE-HASH: 32-byte hash of message
   - SIGNATURE: (r . s) pair
   - PUBLIC-KEY: Point (x . y)

   RETURNS:
   T if signature is valid, NIL otherwise

   ALGORITHM:
   1. Check r, s in range [1, n-1]
   2. w = s^(-1) mod n
   3. u1 = z * w mod n
   4. u2 = r * w mod n
   5. (x, y) = u1*G + u2*Q
   6. Valid if x = r (mod n)"
  (when (point-at-infinity-p public-key)
    (return-from ecdsa-verify nil))
  (let* ((r (car signature))
         (s (cdr signature))
         (n +secp256k1-n+))
    ;; Check r, s in valid range
    (unless (and (< 0 r n) (< 0 s n))
      (return-from ecdsa-verify nil))
    (let* ((z (if (vectorp message-hash)
                  (bytes-to-integer message-hash)
                  message-hash))
           (s-inv (mod-inverse s n))
           (u1 (mod (* z s-inv) n))
           (u2 (mod (* r s-inv) n))
           (point (point-add
                   (point-multiply u1 (generator-point))
                   (point-multiply u2 public-key))))
      (and (not (point-at-infinity-p point))
           (= r (mod (car point) n))))))

(defun ecdsa-verify-hash (hash signature public-key)
  "Verify signature on a pre-computed hash. Alias for ECDSA-VERIFY."
  (ecdsa-verify hash signature public-key))

;;; ============================================================================
;;; DER Signature Encoding
;;; ============================================================================

(defun der-encode-signature (r s)
  "Encode signature (r, s) in DER format.

   DER format: 0x30 <total-len> 0x02 <r-len> <r-bytes> 0x02 <s-len> <s-bytes>

   PARAMETERS:
   - R, S: Signature components (integers)

   RETURNS:
   DER-encoded signature as byte vector"
  (flet ((encode-integer (n)
           (let* ((bytes (integer-to-bytes n 32))
                  ;; Remove leading zeros
                  (start (position-if #'plusp bytes))
                  (trimmed (if start (subseq bytes start) (vector 0))))
             ;; Add leading zero if high bit is set (to indicate positive)
             (if (>= (aref trimmed 0) #x80)
                 (concatenate '(vector (unsigned-byte 8)) (vector 0) trimmed)
                 trimmed))))
    (let* ((r-bytes (encode-integer r))
           (s-bytes (encode-integer s))
           (r-len (length r-bytes))
           (s-len (length s-bytes))
           (total-len (+ 2 r-len 2 s-len))
           (result (make-array (+ 2 total-len) :element-type '(unsigned-byte 8))))
      ;; SEQUENCE header
      (setf (aref result 0) #x30
            (aref result 1) total-len)
      ;; R INTEGER
      (setf (aref result 2) #x02
            (aref result 3) r-len)
      (replace result r-bytes :start1 4)
      ;; S INTEGER
      (setf (aref result (+ 4 r-len)) #x02
            (aref result (+ 5 r-len)) s-len)
      (replace result s-bytes :start1 (+ 6 r-len))
      result)))

(defun der-decode-signature (der)
  "Decode DER encoded signature to (r . s) pair.

   PARAMETERS:
   - DER: DER-encoded signature bytes

   RETURNS:
   (r . s) pair

   SIGNALS ERROR:
   If DER format is invalid"
  (unless (and (>= (length der) 8)
               (= (aref der 0) #x30)
               (= (aref der 2) #x02))
    (error "Invalid DER signature format"))
  (let* ((r-len (aref der 3))
         (r (bytes-to-integer (subseq der 4 (+ 4 r-len))))
         (s-start (+ 4 r-len)))
    (unless (= (aref der s-start) #x02)
      (error "Invalid DER signature: missing S integer tag"))
    (let* ((s-len (aref der (1+ s-start)))
           (s (bytes-to-integer (subseq der (+ 2 s-start) (+ 2 s-start s-len)))))
      (cons r s))))

;;; ============================================================================
;;; Compact Signature Encoding
;;; ============================================================================

(defun compact-encode-signature (r s)
  "Encode signature in compact 64-byte format (r || s).

   PARAMETERS:
   - R, S: Signature components (integers)

   RETURNS:
   64-byte vector (32 bytes r, 32 bytes s)"
  (let ((result (make-array 64 :element-type '(unsigned-byte 8))))
    (replace result (integer-to-bytes r 32))
    (replace result (integer-to-bytes s 32) :start1 32)
    result))

(defun compact-decode-signature (bytes)
  "Decode compact 64-byte signature to (r . s) pair.

   PARAMETERS:
   - BYTES: 64-byte signature

   RETURNS:
   (r . s) pair"
  (unless (= (length bytes) 64)
    (error "Invalid compact signature length: expected 64, got ~D" (length bytes)))
  (cons (bytes-to-integer (subseq bytes 0 32))
        (bytes-to-integer (subseq bytes 32 64))))
